export const FETCH_VERSES_DATA = 'FETCH_VERSES_DATA';
export const FETCH_SURAHS_NAME = 'FETCH_SURAHS_NAME';
export const FETCH_CHAPTERS = 'FETCH_CHAPTERS';
export const OPEN_DRAWER = 'OPEN_DRAWER';

export const TRANSITION_MODE = 'TRANSITION_MODE';
export const TRANSITION_LANGUAGE = 'TRANSITION_LANGUAGE';
export const SELECT_BANGLA_TRANSITION = 'SELECT_BANGLA_TRANSITION';

export const SELECT_TAFSEER = 'SELECT_TAFSEER';

export const ARABIC_FONT_SIZE = 'ARABIC_FONT_SIZE';
export const ENGLISH_FONT_SIZE = 'ENGLISH_FONT_SIZE';
export const BANGLA_FONT_SIZE = 'BANGLA_FONT_SIZE';
export const TAFSEER_FONT_SIZE = 'TAFSEER_FONT_SIZE';
